# 1 "test.h"
# 1 "<command-line>"
# 1 "test.h"


# 1 "cloak.h" 1
# 4 "test.h" 2



EXPR_2( EXPAND(EXPAND(EXPAND(EXPAND(EXPAND(EXPAND( 0) 1) 2) 3) 4) 5) 6 ) 7 8
# 18 "test.h"
 template< class , class> class T0 , template< class , class , class> class T1 , template< class , class , class , class> class T2 , template< class , class , class , class , class> class T3



 0 1 2 3 4 5 6 7
# 43 "test.h"
8 7 6 5 4 3 2 1
# 61 "test.h"
8 7 6 5 4 3 2 1
